#!/bin/bash
# /etc/init.d/camera

### BEGIN INIT INFO
# Provides:          camera interface
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to take pictures
### END INIT INFO
danger=90
usep=$(echo $(df -h / | grep / | awk '{ print $5}' | sed 's/%//g'))
if [ "$usep" -le "$danger" ]; then
	DATE=$(date +"%Y-%m-%d_%H%M")
	raspistill -ex night -o /var/www/photos/$DATE.jpg
fi
